### ISSUE TITLE
IDA 7.7  Go(1.10.x-1.17.x)[EXEC AMD64-64] Restore failed

### ISSUE THREAD

**Issue by immune53** [0xjiayu/go_parser#25]
I use detect it easy scan the program,display  Go(1.10.x-1.17.x)[EXEC AMD64-64],when I use go_parser restore,hava error break 

G:\IDAPlugins\go_parser\go_parser.py: Failed to find firstmoduledata address!
Traceback (most recent call last):
  File "E:\Tools\IDA_Pro_7.7\python\3\ida_idaapi.py", line 580, in IDAPython_ExecScript
    exec(code, g)
  File "G:/IDAPlugins/go_parser/go_parser.py", line 56, in <module>
    main()
  File "G:/IDAPlugins/go_parser/go_parser.py", line 29, in main
    firstmoddata_addr, magic_number = moduledata.find_first_moduledata_addr()
  File "G:\IDAPlugins/go_parser\moduledata.py", line 177, in find_first_moduledata_addr
    raise Exception("Failed to find firstmoduledata address!")
Exception: Failed to find firstmoduledata address!

**Comment by 0xjiayu** [comment]
That should be a malformed binary, usually with a modified magic number. go_parser can't do anything about it unless you find the real magic number inside the binary, and modify the magic number in go_parser accordingly.
