### ISSUE TITLE
没有任何安装的文档么？

### ISSUE THREAD

**Issue by nkbai** [0xjiayu/go_parser#3]

**Comment by nkbai** [comment]
直接复制py文件到plugins目录，结果ida启动不起来了。 系统是mac 10.15.7， ida 是7.0

**Comment by 0xjiayu** [comment]
IDAPro 的 Script File，不是 Plugin。所以不是你上述描述的用法。

Win 版的 IDA，可以打开一个 Go 二进制文件后，直接按 [Alt+F7] 快捷键，指定 go_parser.py ，执行本套脚本（注意是直接执行，不是载入后还有别的操作选项）。

不用快捷键的操作，在菜单栏里用鼠标点击：File-->Script file，Mac 版同理：
![ida_scriptfile](https://user-images.githubusercontent.com/4980416/94502954-e5652500-0237-11eb-9668-8d2e09f8ca3c.png)

**Comment by nkbai** [comment]
/Users/bai/Downloads/go_parser/go_parser.py: global name 'common' is not defined
Traceback (most recent call last):
  File "/Applications/ida64.app/Contents/MacOS/python/ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "/Users/bai/Downloads/go_parser/go_parser.py", line 52, in <module>
    main()
  File "/Users/bai/Downloads/go_parser/go_parser.py", line 29, in main
    firstmoddata_addr = moduledata.find_first_moduledata_addr()
  File "/Applications/ida.app/Contents/MacOS/plugins/moduledata.py", line 53, in find_first_moduledata_addr
  File "/Applications/ida.app/Contents/MacOS/plugins/moduledata.py", line 12, in is_stripped
NameError: global name 'common' is not defined

**Comment by nkbai** [comment]
```
/Users/bai/Downloads/go_parser/go_parser.py: global name 'common' is not defined
Traceback (most recent call last):
  File "/Applications/ida64.app/Contents/MacOS/python/ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "/Users/bai/Downloads/go_parser/go_parser.py", line 52, in <module>
    main()
  File "/Users/bai/Downloads/go_parser/go_parser.py", line 29, in main
    firstmoddata_addr = moduledata.find_first_moduledata_addr()
  File "/Applications/ida.app/Contents/MacOS/plugins/moduledata.py", line 53, in find_first_moduledata_addr
  File "/Applications/ida.app/Contents/MacOS/plugins/moduledata.py", line 12, in is_stripped
NameError: global name 'common' is not defined

```

直接运行行不通

**Comment by 0xjiayu** [comment]
抱歉，白天我手头只有 Windows，所以无法测试并及时回复。晚上用 IDA7.0 for Mac (macOS 10.15.6)测试，并没有复现你描述的问题。

可以详细描述下导致上面问题发生的操作步骤吗？

方便的话，我想看一下你用来分析的样本。如果是 VT 上存在的样本，只发我一个 MD5 即可。Thanks

**Comment by nszy007** [comment]
我使用windows版和mac版的7.0ida加载都出现报错：
`\\mac\Home\Desktop\go_parser\go_parser-1.0.0\go_parser.py: in method 'create_strlit', argument 2 of type 'size_t'
Traceback (most recent call last):
  File "C:\Program Files\IDA 7.0\python\ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "//mac/Home/Desktop/go_parser/go_parser-1.0.0/go_parser.py", line 52, in <module>
    main()
  File "//mac/Home/Desktop/go_parser/go_parser-1.0.0/go_parser.py", line 36, in main
    pclntab.parse()
  File "//mac/Home/Desktop/go_parser/go_parser-1.0.0\pclntbl.py", line 173, in parse
    self.parse_funcs()
  File "//mac/Home/Desktop/go_parser/go_parser-1.0.0\pclntbl.py", line 125, in parse_funcs
    func_st.parse()
  File "//mac/Home/Desktop/go_parser/go_parser-1.0.0\pclntbl.py", line 252, in parse
    if idc.MakeStr(name_addr, name_addr + len(raw_name_str) + 1):
  File "C:\Program Files\IDA 7.0\python\idc_bc695.py", line 113, in MakeStr
    def MakeStr(ea, endea): return create_strlit(ea, 0 if (endea) == ida_idaapi.BADADDR else endea-ea)
  File "C:\Program Files\IDA 7.0\python\idc.py", line 695, in create_strlit
    return ida_bytes.create_strlit(ea, 0 if endea == BADADDR else endea - ea, get_inf_attr(INF_STRTYPE))
  File "C:\Program Files\IDA 7.0\python\ida_bytes.py", line 1618, in create_strlit
    return _ida_bytes.create_strlit(*args)
TypeError: in method 'create_strlit', argument 2 of type 'size_t'`

分析样本地址是：
https://github.com/chaitin/xray/releases/download/1.3.3/xray_linux_arm64.zip

**Comment by 0xjiayu** [comment]
> 师傅，我使用windows版和mac版的7.0ida加载都出现报错：
> `\\mac\Home\Desktop\go_parser\go_parser-1.0.0\go_parser.py: in method 'create_strlit', argument 2 of type 'size_t' Traceback (most recent call last): File "C:\Program Files\IDA 7.0\python\ida_idaapi.py", line 553, in IDAPython_ExecScript execfile(script, g) File "//mac/Home/Desktop/go_parser/go_parser-1.0.0/go_parser.py", line 52, in <module> main() File "//mac/Home/Desktop/go_parser/go_parser-1.0.0/go_parser.py", line 36, in main pclntab.parse() File "//mac/Home/Desktop/go_parser/go_parser-1.0.0\pclntbl.py", line 173, in parse self.parse_funcs() File "//mac/Home/Desktop/go_parser/go_parser-1.0.0\pclntbl.py", line 125, in parse_funcs func_st.parse() File "//mac/Home/Desktop/go_parser/go_parser-1.0.0\pclntbl.py", line 252, in parse if idc.MakeStr(name_addr, name_addr + len(raw_name_str) + 1): File "C:\Program Files\IDA 7.0\python\idc_bc695.py", line 113, in MakeStr def MakeStr(ea, endea): return create_strlit(ea, 0 if (endea) == ida_idaapi.BADADDR else endea-ea) File "C:\Program Files\IDA 7.0\python\idc.py", line 695, in create_strlit return ida_bytes.create_strlit(ea, 0 if endea == BADADDR else endea - ea, get_inf_attr(INF_STRTYPE)) File "C:\Program Files\IDA 7.0\python\ida_bytes.py", line 1618, in create_strlit return _ida_bytes.create_strlit(*args) TypeError: in method 'create_strlit', argument 2 of type 'size_t'`
> 
> 分析样本地址是：
> https://github.com/chaitin/xray/releases/download/1.3.3/xray_linux_arm64.zip

看这里 👉： https://github.com/0xjiayu/go_parser/issues/5

**Comment by nszy007** [comment]
> > 师傅，我使用windows版和mac版的7.0ida加载都出现报错：
> > `\\mac\Home\Desktop\go_parser\go_parser-1.0.0\go_parser.py: in method 'create_strlit', argument 2 of type 'size_t' Traceback (most recent call last): File "C:\Program Files\IDA 7.0\python\ida_idaapi.py", line 553, in IDAPython_ExecScript execfile(script, g) File "//mac/Home/Desktop/go_parser/go_parser-1.0.0/go_parser.py", line 52, in <module> main() File "//mac/Home/Desktop/go_parser/go_parser-1.0.0/go_parser.py", line 36, in main pclntab.parse() File "//mac/Home/Desktop/go_parser/go_parser-1.0.0\pclntbl.py", line 173, in parse self.parse_funcs() File "//mac/Home/Desktop/go_parser/go_parser-1.0.0\pclntbl.py", line 125, in parse_funcs func_st.parse() File "//mac/Home/Desktop/go_parser/go_parser-1.0.0\pclntbl.py", line 252, in parse if idc.MakeStr(name_addr, name_addr + len(raw_name_str) + 1): File "C:\Program Files\IDA 7.0\python\idc_bc695.py", line 113, in MakeStr def MakeStr(ea, endea): return create_strlit(ea, 0 if (endea) == ida_idaapi.BADADDR else endea-ea) File "C:\Program Files\IDA 7.0\python\idc.py", line 695, in create_strlit return ida_bytes.create_strlit(ea, 0 if endea == BADADDR else endea - ea, get_inf_attr(INF_STRTYPE)) File "C:\Program Files\IDA 7.0\python\ida_bytes.py", line 1618, in create_strlit return _ida_bytes.create_strlit(*args) TypeError: in method 'create_strlit', argument 2 of type 'size_t'`
> > 分析样本地址是：
> > https://github.com/chaitin/xray/releases/download/1.3.3/xray_linux_arm64.zip
> 
> 看这里 👉： #5

已解决，谢谢师傅
