### ISSUE TITLE
TypeError: in method 'create_strlit', argument 2 of type 'size_t'

### ISSUE THREAD

**Issue by EXHades** [0xjiayu/go_parser#5]
- 52 的便携版 IDA 7.0
- 打开 Go 二进制文件，直接 Alt+F7 选择 go_parser.py 后报错如下 
```
Z:\windows\IDAScriptFile\go_parser\go_parser.py: in method 'create_strlit', argument 2 of type 'size_t'
Traceback (most recent call last):
  File "C:\Users\testUser\Desktop\IDA_Pro_v7.0_Portable\python\ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "Z:/windows/IDAScriptFile/go_parser/go_parser.py", line 52, in <module>
    main()
  File "Z:/windows/IDAScriptFile/go_parser/go_parser.py", line 36, in main
    pclntab.parse()
  File "Z:/windows/IDAScriptFile/go_parser\pclntbl.py", line 173, in parse
    self.parse_funcs()
  File "Z:/windows/IDAScriptFile/go_parser\pclntbl.py", line 125, in parse_funcs
    func_st.parse()
  File "Z:/windows/IDAScriptFile/go_parser\pclntbl.py", line 252, in parse
    if idc.MakeStr(name_addr, name_addr + len(raw_name_str) + 1):
  File "C:\Users\testUser\Desktop\IDA_Pro_v7.0_Portable\python\idc_bc695.py", line 113, in MakeStr
    def MakeStr(ea, endea): return create_strlit(ea, 0 if (endea) == ida_idaapi.BADADDR else endea-ea)
  File "C:\Users\testUser\Desktop\IDA_Pro_v7.0_Portable\python\idc.py", line 695, in create_strlit
    return ida_bytes.create_strlit(ea, 0 if endea == BADADDR else endea - ea, get_inf_attr(INF_STRTYPE))
  File "C:\Users\testUser\Desktop\IDA_Pro_v7.0_Portable\python\ida_bytes.py", line 1618, in create_strlit
    return _ida_bytes.create_strlit(*args)
TypeError: in method 'create_strlit', argument 2 of type 'size_t'
```

**Comment by 0xjiayu** [comment]
这个是 IDA7.0 自带的 IDAPython 的问题，已 Close 的一个 issue 里提到过 👉： https://github.com/0xjiayu/go_parser/issues/1#issuecomment-689369681

**Comment by EXHades** [comment]
谢谢，解决了
