### ISSUE TITLE
ida7.5+py3 error

### ISSUE THREAD

**Issue by p1v07** [0xjiayu/go_parser#6]
```
F:\tools\go_parser\go_parser.py: module 'idc' has no attribute 'Dword'
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.5\python\3\ida_idaapi.py", line 615, in IDAPython_ExecScript
    exec(code, g)
  File "F:/tools/go_parser/go_parser.py", line 52, in <module>
    main()
  File "F:/tools/go_parser/go_parser.py", line 29, in main
    firstmoddata_addr = moduledata.find_first_moduledata_addr()
  File "F:/tools/go_parser\moduledata.py", line 71, in find_first_moduledata_addr
    if idc.Dword(read_mem(curr_addr, read_only=True)) & 0xFFFFFFFF == magic_num: # possible firstmoduledata
AttributeError: module 'idc' has no attribute 'Dword'
```

**Comment by 0xjiayu** [comment]
Please try this branch for Py3 and IDA7.4+:
https://github.com/0xjiayu/go_parser/tree/py3

**Comment by p1v07** [comment]
The same error occurred

**Comment by 0xjiayu** [comment]
But there is NO `idc.Dword()` call in **moduledata.py** of the Py3 branch:

https://github.com/0xjiayu/go_parser/blob/py3/moduledata.py#L71

Please check the source code branch which you run. Have you mixed the two branches?

**Comment by p1v07** [comment]
My bad. Thank you so much.

**Comment by 0xjiayu** [comment]
You are welcome.
