### ISSUE TITLE
ida7.5下测试报错

### ISSUE THREAD

**Issue by nszy007** [0xjiayu/go_parser#7]
```
/media/psf/Home/Documents/code/python/go_parser/go_parser-1.0.0-py3/go_parser.py: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Traceback (most recent call last):
  File "/media/psf/Home/Documents/tools/ida7.5/python/3/ida_idaapi.py", line 615, in IDAPython_ExecScript
    exec(code, g)
  File "/media/psf/Home/Documents/code/python/go_parser/go_parser-1.0.0-py3/go_parser.py", line 53, in <module>
    main()
  File "/media/psf/Home/Documents/code/python/go_parser/go_parser-1.0.0-py3/go_parser.py", line 36, in main
    pclntab.parse()
  File "/media/psf/Home/Documents/code/python/go_parser/go_parser-1.0.0-py3/pclntbl.py", line 175, in parse
    self.goroot = common.get_goroot()
  File "/media/psf/Home/Documents/code/python/go_parser/go_parser-1.0.0-py3/common.py", line 167, in get_goroot
    goroot_path_str = idc.get_bytes(goroot_path_addr, goroot_path_len).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by wonderkun** [comment]
识别出来的goroot_path_addr 有非法字符，可能是 goroot_path_addr 这个地址识别错误，你能提供一下go的二进制吗？ 我debug一下看看。

**Comment by nszy007** [comment]
我就尝试的这个：
https://github.com/chaitin/xray/releases/download/1.4.5/xray_linux_arm64.zip
在ida7.0下是没问题的。

**Comment by wonderkun** [comment]
@0xjiayu  arm架构的go，goParse可以解析吗？

**Comment by 0xjiayu** [comment]
> @0xjiayu arm架构的go，goParse可以解析吗？

总体可以解析的，在 IDA7.2 下我测试了上面的 XRay 文件，firstmoduledata/pclntab 这些结构解析没问题，源码文件路径列表、函数符号以及运行时类型信息的解析都没问题。

只是有两点解析不好：
1. GOROOT 路径解析不对。go_parser 里面现有的 GOROOT 解析方式是先解析函数符号、再通过解析 runtime.GOROOT() 这个函数的 Call Graph，然后提取 GOROOT 路径字符串的地址和长度来提取 GOROOT 字符串。已有的方式是针对 x86 架构的二进制文件来实现，解析 ARM 的二进制文件时，应该是 GOROOT 地址和长度提取的不对，所以才会报错。这一点等我有时间研究一下，争取尽快解决；
2. 程序中用到的字符串解析不好。这一点再 README 中已经强调了，目前的字符串解析，只针对 x86 架构的二进制文件。这一点应该不会引起报错。这一点优先级靠后一些，因为工作量比较大，相对来说算个苦力活，等有大块时间了再完善针对多架构 CPU 的二进制文件字符串解析。
