### ISSUE TITLE
ida7.0报错

### ISSUE THREAD

**Issue by Hao17** [0xjiayu/go_parser#8]
C:\Desktop\go_parser-master\go_parser-master\go_parser.py: in method 'create_strlit', argument 2 of type 'size_t'
Traceback (most recent call last):
  File "C:\AnalysisTools\IDA_Pro_v7.0\python\ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Desktop/go_parser-master/go_parser-master/go_parser.py", line 52, in <module>
    main()
  File "C:/Desktop/go_parser-master/go_parser-master/go_parser.py", line 36, in main
    pclntab.parse()
  File "C:/Desktop/go_parser-master/go_parser-master\pclntbl.py", line 173, in parse
    self.parse_funcs()
  File "C:/Desktop/go_parser-master/go_parser-master\pclntbl.py", line 125, in parse_funcs
    func_st.parse()
  File "C:/Desktop/go_parser-master/go_parser-master\pclntbl.py", line 252, in parse
    if idc.MakeStr(name_addr, name_addr + len(raw_name_str) + 1):
  File "C:\AnalysisTools\IDA_Pro_v7.0\python\idc_bc695.py", line 113, in MakeStr
    def MakeStr(ea, endea): return create_strlit(ea, 0 if (endea) == ida_idaapi.BADADDR else endea-ea)
  File "C:\AnalysisTools\IDA_Pro_v7.0\python\idc.py", line 695, in create_strlit
    return ida_bytes.create_strlit(ea, 0 if endea == BADADDR else endea - ea, get_inf_attr(INF_STRTYPE))
  File "C:\AnalysisTools\IDA_Pro_v7.0\python\ida_bytes.py", line 1618, in create_strlit
    return _ida_bytes.create_strlit(*args)
TypeError: in method 'create_strlit', argument 2 of type 'size_t'

**Comment by 0xjiayu** [comment]
解决方法参考这里：**https://github.com/0xjiayu/go_parser/issues/5**

**Comment by Hao17** [comment]
已解决，感谢
