### ISSUE TITLE
ida 7.5报错- -

### ISSUE THREAD

**Issue by iiiusky** [0xjiayu/go_parser#9]
C:\Users\xx\Desktop\go_parser-1.0.0-py3\go_parser.py: No module named 'IPython'
Traceback (most recent call last):
  File "C:\Users\xx\Desktop\IDA_Pro_v7.5_Portable\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/xx/Desktop/go_parser-1.0.0-py3/go_parser.py", line 24, in <module>
    idaapi.require("types_builder")
  File "C:\Users\xx\Desktop\IDA_Pro_v7.5_Portable\python\3\ida_idaapi.py", line 161, in require
    m = importlib.import_module(modulename, package)
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/Users/sky/Desktop/go_parser-1.0.0-py3\types_builder.py", line 12, in <module>
    import IPython
ModuleNotFoundError: No module named 'IPython'

**Comment by wonderkun** [comment]
脚本中导入了IPython这个库，你手工去掉，或者自己安装一下。
